apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-service
  labels:
    app: user-management-service
#desired state of the Deployment
spec:
  #number of replicas (pods) for the Deployment
  replicas: 1
  #how the Deployment identifies which pods to manage
  selector:
    matchLabels:
      app: user-management-service
  #describes the pods that will be created
  template:
    metadata:
      labels:
        app: user-management-service
    spec:
      #containers within the pod
      containers:
        - name: user-management-service
          #Docker image to use for the container
          image: gcr.io/PROJECT_ID/IMAGE:TAG  # Replace with your Docker Hub image and tag
          #when to pull the container image.
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          #Resource requests and limits for the container
          resources:
            requests:
              cpu: "50m"
              memory: "80Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"